class Localization
  EN: 
    name: "En"
    title1:	"EDD Calculator"
    title2:	"Results"
    title3: "Home Visit Schedule"
    title4: "BI-WEEKLY HOME VISIT"
    title5: "BP MONITORING"
    title6: "HB MONITORING"
    button1: "Initial"
    button2: "Randomization"
    button3: "Calculate"
    button4: "Clear"
    inputLabel1: "Today's Date"
    inputLabel2: "Date of LMP"
    inputLabel3: "Unknown"
    inputLabel4: "Date of US Exam"
    inputLabel5: "GA by US"
    inputLabel6: "Weeks"
    inputLabel7: "Days"
    inputLabel8: "Date of Randomization"
    resultLabel1: "EDD by LMP"
    resultLabel2: "GA by LMP"
    resultLabel3: "Projected EDD"
    resultLabel4: "GA by Projected EDD"
    resultLabel5: "Last Date to Randomize"
    resultLabel6: "Bi-Weekly Visits"
    resultLabel7: "Visit"
    resultLabel8: "Eligibility"
    resultLabel9: "Date of Final Dose"
    wordOR: "or"
    wordAND: "and"
    idCARD: "Participant ID Card"
    eligible: "ELIGIBLE"
    notEligible: "NOT ELIGIBLE"
    select14: "Select 14 card patient kit"
    select15: "Select 15 card patient kit"
    donotDispense: "Do not dispense study medication"
    visitNo: "Visit No."
    plannedDate: "Planned Date"
    comment1: "No Date Calculated"
    weeks: "Weeks"
    bp_monitor0: "Enrollment"
    hb_monitor0: "Screening"
    hb_monitor1: "4 weeks after randomization"
    hb_monitor2: "26-30 weeks GA"
    error: "ERROR"
    errorMsg1: "Require Date of LMP/ Unknown"
    errorMsg2: "Require Date of US"
    errorMsg3: "Require GA by US"
    errorMsg4: "Require Date of Randomization"
    errorMsg5: "Date of Randomization earlier than Current Date"
    errorMsg6: "Date of US Exam cannot be after Today's Date"
    errorMsg7: "Invalid GA by US weeks"
    errorMsg8: "Invalid GA by US days"
    errorMsg9: "Please enter the Date of LMP"
    instructions: "EDD Calculator Instructions"
    close: "Close"

  FR:
    name: "Fr"
    title1: "Calculatrice DPA"
    title2: "Résultats"
    title3: "Visite à Domicile Calendrier"
    title4: "Visite à Domicile Bimensuelles"
    title5: "BP Surveillance"
    title6: "HB Surveillance"
    button1: "Initial"
    button2: "Randomisation"
    button3: "Calculer"
    button4: "Effacer"
    inputLabel1: "Date d’aujourd’hui"
    inputLabel2: "DDR"
    inputLabel3: "Pas connu"
    inputLabel4: "Date d’échographie"
    inputLabel5: "AG par échographie"
    inputLabel6: "Semaines"
    inputLabel7: "Jours"
    inputLabel8: "Date de randomisation"
    resultLabel1: "DPA par DDR"
    resultLabel2: "AG par DDR"
    resultLabel3: "DPA prévue"
    resultLabel4: "AG par DPA prévue"
    resultLabel5: "Dernière date à randomiser"
    resultLabel6: "Visites Bimensuelles"
    resultLabel7: "Visite"
    resultLabel8: "Eligibilité"
    resultLabel9: "Date de Dose Finale"
    wordOR: "ou"
    wordAND: "et"
    idCARD: "Carte d'identité de Participant"
    eligible: "ELIGIBLE"
    notEligible: "NON ELIGIBLE"
    select14: "Sélectionnez 14 carte de kit du patient"
    select15: "Sélectionnez 15 carte de kit du patient"
    donotDispense: "Ne pas distribuer des médicaments de l'étude"
    visitNo: "Visite No."
    plannedDate: "Date de Prévu"
    comment1: "Aucune Date Calculés"
    weeks: "Semaines"
    bp_monitor0: "Inscription"
    hb_monitor0: "Dépistage"
    hb_monitor1: "4 Semaines après Randomisation"
    hb_monitor2: "26-30 Semaines AG"
    error: "ERREUR"
    errorMsg1: "DDR/Inconnu exiger"
    errorMsg2: "Date d’échographie exiger"
    errorMsg3: "AG par échographie exiger"
    errorMsg4: "Date de randomisation exiger"
    errorMsg5: "Date de randomisation plus tôt que la date courante"
    errorMsg6: "Date d’échographie ne peut pas être après date du jour"
    errorMsg7: "Semaines AG par échographie invalide"
    errorMsg8: "Jours AG par échographie invalide"
    errorMsg9: "S'il vous plaît entrez la date de DDR"
    instructions: "Instructions sur la calculateur de la DPA"
    close: "Ferme"

  ES:
    name: "Es"
    title1:	"Calculadora de EG"
    title2:	"Resultados"
    title3: "Cronograma de las visitas a hogares"
    title4: "VISITAS QUINCENALES"
    title5: "MONITOREO DE P/A"
    title6: "MONITOREO DE HB"
    button1: "Inicial"
    button2: "Randomización"
    button3: "Calcular"
    button4: "Borrar"
    inputLabel1: "Fecha de Hoy"
    inputLabel2: "Fecha de ultima regla"
    inputLabel3: "No se sabe"
    inputLabel4: "Fecha del ultrasonido"
    inputLabel5: "EG por US"
    inputLabel6: "Semanas"
    inputLabel7: "Días"
    inputLabel8: "Fecha de Randomización"
    resultLabel1: "FPP por FUR"
    resultLabel2: "EGP por FUR"
    resultLabel3: "Fecha de parto Proyectada"
    resultLabel4: "EG por FP Proyectada"
    resultLabel5: "Ultima fecha para Randomizar"
    resultLabel6: "Visitas Quincenales"
    resultLabel7: "Visita"
    resultLabel8: "Elegibilidad"
    resultLabel9: "Fecha de Ultima Dosis"
    wordOR: "o"
    wordAND: "y"
    idCARD: "Tarjeta de ID de la participante"
    eligible: "ELEGIBLE"
    notEligible: "NO ELEGIBLE"
    select14: "Seleccione kit con 14 Sobres"
    select15: "Seleccione kit con 15 Sobres"
    donotDispense: "No le dé medicamento del estudio"
    visitNo: "Visita No."
    plannedDate: "Fecha planeada"
    comment1: "No se calculó Fecha"
    weeks: "semanas"
    bp_monitor0: "Enrolamiento"
    hb_monitor0: "Tamizaje"
    hb_monitor1: "4 semanas después de randomizada"
    hb_monitor2: "26-30 Semanas EG"
    error: "ERROR"
    errorMsg1: "Se requiere fecha de FUR/ Desconocida"
    errorMsg2: "Se requiere fecha de Ultrasonido"
    errorMsg3: "Se requiere EG por US"
    errorMsg4: "Se requiere Fecha de Randomización"
    errorMsg5: "Fecha de Randomización no puede ser menor a la fecha de HOY"
    errorMsg6: "La fecha de ultrasonido no puede ser después de la fecha de Hoy"
    errorMsg7: "Semanas Gestacionales por US es invalida"
    errorMsg8: "Días de Gestación por US es invalido"
    errorMsg9: "Por favor ingrese fecha de FUR"
    instructions: "Instrucciones de Calculadora de EG"
    close: "Cerrar"

module.exports = Localization